title: "OpenStack Cloud Tutorials"
author: "CloudTutorials"
description: "Step by Step OpenStack Tutorials"
permalink: /articles/:title

github_username: "CloudTutorials"
rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other
